title: akbar.kustirama.id
author: abaykan
email: akbar@kustirama.id
description: > # this means to ignore newlines until "show_exerpts:"
  Another place to write.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Akbar Kustirama
  tagline: Just another place to write
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/yha.jpeg" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "id" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  disqus_shortname: "abaykan"
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    twitter: abaykandotcom
    github:  abaykan
    linkedIn: in/mukhammad-akbar
    #dribbble: jekyll
    #flickr:   jekyll
    instagram: abaykandotcom
    #pinterest: jekyll
    youtube: abaykan
    facebook: abaaaay
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    email: akbar@kustirama.id

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
